// <auto-generated />
using System;
using ExpensesWorker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesWorker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123151931_CreateSellingExpenses79")]
    partial class CreateSellingExpenses79
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesWorker.Domain.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExpenseItems");
                });

            modelBuilder.Entity("ExpensesWorker.Domain.ExpenseValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseItemId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ExpenseValues");
                });

            modelBuilder.Entity("ExpensesWorker.Domain.SellingExpenses79", b =>
                {
                    b.Property<int>("_year")
                        .HasColumnType("int");

                    b.Property<int>("_month")
                        .HasColumnType("int");

                    b.Property<string>("Подразделение")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("НаборСтатей")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Статья")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("СпособДоставки")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("КаналРеализации")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Склад")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Номенклатура_Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CALCBASE")
                        .HasColumnType("float");

                    b.Property<string>("year_month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Вес")
                        .HasColumnType("float");

                    b.Property<double>("Количество")
                        .HasColumnType("float");

                    b.Property<double>("Расчетное_Значение")
                        .HasColumnType("float");

                    b.Property<double>("РублиЗаКг")
                        .HasColumnType("float");

                    b.Property<double>("Сумма")
                        .HasColumnType("float");

                    b.Property<double>("СуммаВыручки")
                        .HasColumnType("float");

                    b.HasKey("_year", "_month", "Подразделение", "НаборСтатей", "Статья", "СпособДоставки", "КаналРеализации", "Склад", "Номенклатура_Key");

                    b.ToTable("Expense_Затраты_по_реализациям_79", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
