// <auto-generated />
using System;
using ExpensesWorker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpensesWorker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpensesWorker.Domain.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExpenseItems", (string)null);
                });

            modelBuilder.Entity("ExpensesWorker.Domain.ExpenseValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseItemId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ExpenseValues", (string)null);
                });

            modelBuilder.Entity("ExpensesWorker.Domain.SellingExpenses", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_month")
                        .HasColumnType("int");

                    b.Property<int>("_year")
                        .HasColumnType("int");

                    b.Property<string>("year_month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("КаналРеализации")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("НаборСтатей")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Номенклатура_Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Подразделение")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Расчетное_Значение")
                        .HasColumnType("float");

                    b.Property<string>("Склад")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("СпособДоставки")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Статья")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Expense_Затраты_по_реализациям", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
